### PR TITLE
Add Built-in Azure Member Address Provider

### PR DESCRIPTION
**Pull request by peterjot**
Issue: https://github.com/hazelcast/hazelcast-azure/issues/24

### CODE REVIEW

**Comment by alparslanavci** [comment]
verify

**Comment by alparslanavci** [comment]
verify

**Comment by alparslanavci** [comment]
@peterjot thanks for the contribution. Did you try if Azure IMDS work to get IP addresses with Standard SKUs? The doc says that it doesn't support: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-ip-addresses-overview-arm#standard

**Comment by alparslanavci** [comment]
@peterjot, we checked and the only valid use case of `MemberAddressProvider` is when you are setting up a cluster using public IP addresses, such as among different resource groups. However, when you setup a cluster like this, the latency will become a problem since you are connecting out of the current subnet. We recommend to use WAN replication in such cases. 

Thank you for your contribution, but there is no need for this enhancement. Sorry for not letting you know before you start working on the issue. 

Closing this PR. Also closes #29.

**Comment by peterjot** [comment]
@alparslanavci  thank you for that detailed explanation

**Pull request closed without merging**
