### PR TITLE
Update explanation of tag property in README

### PR DESCRIPTION
**Pull request by mtyazici**
The Azure Discovery SPI uses network interface cards to find VM instances on Azure. So filtering with tags are done on network interface cards. This PR updates the explanation of `tag` property to guide the user correctly.

### CODE REVIEW

**Review by leszko — APPROVED** [review]

**Review by alparslanavci — COMMENTED** [review]
I think it might be better to use `network interfaces` instead of `network interface cards`. Maybe we can also add `(NIC)` in parentheses.

**Comment by alparslanavci** [comment]
Official Azure docs also use the `network interfaces` wording: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-network-interface

**Comment by mtyazici** [comment]
Ok, in the documentation it is `network interfaces` but on the Azure CLI we use it as `az network nic list`. I will use network interfaces then put NIC in parantheses.

**Review by alparslanavci — APPROVED** [review]
Yes, this is the way I described 👍

**Pull request merged**
